#!/usr/bin/env sh

executable=$1
arch=${ARCH:-x86_64}
qemu=${QEMU:-qemu-system-$arch}

# Make a GRUB ISO.
if $(type grub-mkrescue >/dev/null 2>&1); then
  (
    rm -rf target/iso
    mkdir -p target/iso/boot/grub
    cp grub.cfg target/iso/boot/grub/
    cp "$executable" target/iso/georgix

    if [ -d /usr/lib/grub/i386-pc ]; then
      grub-mkrescue -d /usr/lib/grub/i386-pc -o target/georgix.iso target/iso/
    else
      grub-mkrescue -o target/georgix.iso target/iso/
    fi
  ) >/dev/null 2>&1
else
  echo "grub-mkrescue -o target/georgix.iso target/iso/" >&2
  echo "grub-mkrescue: command not found" >&2
  exit 1
fi

# Run it in QEMU.
#
# If running tests, provide a debug exit device and translate exit code 33 to 0.
if [ "$(basename "$(dirname "$executable")")" = "deps" ]; then
  $qemu -cdrom target/georgix.iso -serial stdio -device isa-debug-exit,iobase=0xf4,iosize=0x4 -display none

  status=$?

  if [ $status -eq 33 ]; then
    exit 0
  else
    exit $status
  fi
else
  exec $qemu -cdrom target/georgix.iso -serial stdio -display none
fi
