[build]
target = "targets/x86_64-unknown-georgix-gnu.json"

[target."x86_64-unknown-georgix-gnu"]
rustflags = ["-C", "link-arg=-Tsrc/arch/x86_64/linker.ld"]
runner = "util/run"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
